version: '3'

services:
  spring-app:
    container_name: my_spring_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/wndb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    command: ["java", "-jar", "/app/app.jar"]

  mysql:
    container_name: my_mysql_db
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: wndb
      MYSQL_ROOT_PASSWORD: 12345678

  redis:
    container_name: my_redis
    image: redis:latest
    ports:
      - "6379:6379"
